# Generated by Django 2.1.7 on 2019-04-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doubanapp', '0002_phonedb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonedb',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
