# Generated by Django 2.1.7 on 2019-04-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doubanapp', '0003_auto_20190409_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='db',
            name='director',
            field=models.CharField(default='', max_length=20),
        ),
    ]
