# Generated by Django 2.1.7 on 2019-04-22 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doubanapp', '0004_db_director'),
    ]

    operations = [
        migrations.RenameField(
            model_name='db',
            old_name='director',
            new_name='detail',
        ),
    ]
