# Generated by Django 2.1.7 on 2019-04-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doubanapp', '0006_auto_20190422_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='db',
            old_name='detail',
            new_name='detail1',
        ),
        migrations.AddField(
            model_name='db',
            name='detail2',
            field=models.CharField(default='', max_length=200),
        ),
    ]
