# Generated by Django 2.1.7 on 2019-06-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doubanapp', '0008_phonedb_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='weibodb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranktop', models.CharField(max_length=100)),
                ('title', models.CharField(default='', max_length=100)),
                ('toh', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
