# Generated by Django 2.1.7 on 2019-06-16 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doubanapp', '0009_weibodb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weibodb',
            name='ranktop',
        ),
    ]
